import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,deviceScaleFactor:1});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:8772/?touch');
 await page.waitForFunction(()=>window.__game);
 assert.equal(await page.evaluate(()=>document.querySelector('.menuBox').scrollWidth<=document.querySelector('.menuBox').clientWidth+1),true);
 await page.locator('#btnStart').click();
 await page.waitForFunction(()=>__game.playing);
 const cdp=await context.newCDPSession(page);
 const center=async selector=>{const b=await page.locator(selector).boundingBox();return {x:b.x+b.width/2,y:b.y+b.height/2};};
 const a=await center('.fire-left'),b=await center('.fire-right');
 const touch=async(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});
 await touch('touchStart',[{...a,id:1}]);
 assert.equal(await page.evaluate(()=>__game.player.touch.fire),true);
 await touch('touchStart',[{...a,id:1},{...b,id:2}]);
 await touch('touchEnd',[{...b,id:2}]);
 assert.equal(await page.evaluate(()=>__game.player.touch.fire),true,'releasing one finger preserves other trigger');
 await touch('touchCancel',[]);
 assert.equal(await page.evaluate(()=>__game.player.touch.fire),false,'cancel clears firing');
 await page.locator('.weapon-2').tap();
 await page.waitForFunction(()=>__game.player.slot===2);
 await page.waitForTimeout(550);
 await page.locator('.weapon-3').tap();
 await page.waitForFunction(()=>__game.player.slot===3);
 const pad=await center('.move-pad');
 await touch('touchStart',[{...pad,id:3}]);
 await touch('touchMove',[{x:pad.x,y:pad.y-30,id:3}]);
 assert.ok(await page.evaluate(()=>__game.player.touch.mz>.5));
 await touch('touchCancel',[]);
 assert.equal(await page.evaluate(()=>__game.player.touch.mz),0);
 await touch('touchStart',[{...a,id:4}]);
 await page.evaluate(()=>__game.pause());
 assert.equal(await page.evaluate(()=>__game.player.touch.fire),false);
 await touch('touchEnd',[]);
 await page.locator('#btnResume').tap();
 await page.setViewportSize({width:852,height:393});
 const inside=await page.evaluate(()=>[...document.querySelectorAll('#touch button,.move-pad')].every(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}));
 assert.equal(inside,true,'landscape controls fit');
 await page.screenshot({path:'/tmp/transport-landscape-optimized.png'});
 const scaling=await page.evaluate(()=>{const r=__game.renderer;for(let i=0;i<100;i++)r.sampleFrame(1/30,true);const down=r.resolutionScale;for(let i=0;i<1200;i++)r.sampleFrame(1/60,true);return {down,up:r.resolutionScale};});
 assert.ok(scaling.down<1);assert.ok(scaling.up>scaling.down);assert.ok(scaling.up<=1);
 assert.deepEqual(errors,[]);
 console.log('PASS: menu fit, dual fire, cancellation, knife/grenade, movement reset, pause reset, landscape fit, adaptive resolution, no page errors');
}finally{await browser.close();}
